PyChat/urls.py
from django.contrib import admin
from django.urls import path, include
from registration import views as rv

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("chat.urls")),
    path('signup/', rv.SignUp, name="register"),
    path('editprofile/', rv.EditProfile, name="editprofile"),
    path("", include("django.contrib.auth.urls")),
    path('account/',include('accounts.urls')),
]

accounts/urls.py
from . import views
from django.contrib.auth.views import (
LoginView,
LogoutView,
PasswordResetView,
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView,
)
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    # path("chat",include("chat.urls")),

    path('',views.home,name="home"),
    path('load',views.index,name="form"),
    path('form',views.my_form,name="form"),
    path('interested',views.preference_form,name="interested"),
    
    path('recommendation',views.falseRecommendation,name="falseRecommendation"),
    path('showrecommendation',views.showRecommendation,name="showRecommendation"),

    path('login',LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout',LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),
    path('profile',views.profile,name='profile'),
    path('change_password',views.change_password,name='change_password'),
    path('reset-password', PasswordResetView.as_view(template_name='accounts/reset_password.html'),name='reset_password'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),      

]
#    python -m smtpd -n -c DebuggingServer localhost:1025
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import (
LoginView,
LogoutView,
PasswordResetView,
PasswordResetDoneView,
PasswordResetConfirmView,
PasswordResetCompleteView,
)
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path("", views.index, name="index"),
    path("chatstart/",views.chatstart, name="chatstart"),
    path("search/", views.search, name="search"),
    path("addfriend/<str:name>", views.addFriend, name="addFriend"),
    path("removefriend/<str:name>", views.removeFriend, name="removeFriend"),
    path("chat/<str:username>", views.chat, name="chat"),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import uuid
from accounts.occuption import occuption_choices
from accounts.languages import language_choices
from multiselectfield import MultiSelectField

religion_choices = (
    ('None','None'),
    ('Islam','Islam'),
    ('Hindu', 'Hindu'),
    ('Jain','Jain'),
    ('Christian','Christian'),
    ('Zoroastrianism','Zoroastrianism'),
    ('Sikh','Sikh'),
    ('Buddhist','Buddhist'),
)

gender_choices = (
    ('Other','Other(Both)'),
    ('Male','Male'),
    ('Female','Female'),
)

education_choices = (
    ('10th','10th'),
    ('12th','12th'),
    ('Diploma','Diploma'),
    ('B.Tech','B.Tech'),
    ('M.Tech','M.Tech'),
    ('PHD','PHD'),
    ('Post Doctorate','Post Doctorate'),
)

class UploadedImage1(models.Model):
    title = models.CharField(primary_key=True, max_length=150, help_text='Enter an image title')
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

class Show(models.Model):
    username = models.CharField( max_length=150,primary_key=True)
    age  = models.FloatField()
    height = models.CharField(max_length=120)
    Country = models.CharField(max_length=120,blank=True)
    City = models.CharField(max_length=120,blank=True)
    Distance = models.FloatField(max_length=120)
    education = models.CharField(max_length=120,choices=education_choices, default='NA')
    gender = models.CharField(max_length=6,choices=gender_choices, default='NA')
    religion = models.CharField(max_length=120, choices=religion_choices, default='NA')
    occuption = models.CharField(max_length=120, choices=occuption_choices, default='NA') 
    def __str__(self):
        return self.username

class alllang(models.Model):
    languages = models.CharField(max_length=120, choices=language_choices, default='NA')

    def __str__(self):
        return self.languages

class Preference_show(models.Model):
    username = models.CharField('Username', max_length=150,primary_key=True)
    min_height = models.CharField("Min height",max_length=120)
    max_height = models.CharField("Max height",max_length=120)
    min_age = models.FloatField("Min age in years",default= None, null=True, blank=True)
    max_age = models.FloatField("Max age in years",default= None, null=True, blank=True)
    gender = models.CharField('gender',max_length=6,choices=gender_choices, default='NA')
    religion = models.CharField(max_length=120, choices=religion_choices, default='NA')
    Hobbies = models.CharField(max_length=120,blank=True)
    Language = models.ManyToManyField(alllang,max_length=120)
    # Language = MultiSelectField(max_length=120, choices=language_choices, default='NA')

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import *



class UploadImageForm(forms.ModelForm):   
    class Meta: 
        model = UploadedImage1
        fields = ['image', 'title']

class MyForm(forms.ModelForm):
  class Meta:
    model = Show
    fields = ["username", "age","height","Country","City","Distance","education","gender","religion","occuption"]
    labels = {"age":"Age in years","height":"Height in feet"}

class PreferenceForm(forms.ModelForm):
  class Meta:
    model = Preference_show
    fields = ["username","min_height","max_height","min_age","max_age","gender","religion","Hobbies","Language"]


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
        "username",
        'first_name',
        'last_name',
        'email',
        'password1',
        'password2'
        )
    def save(self,commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email',
        'first_name',
        'last_name',
        'password'
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from accounts.forms import (
    RegistrationForm,
    EditProfileForm
)
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from .models import *
from .forms import *
from django.core.files.storage import FileSystemStorage
from .find_dist_btw_cities import *
from geopy.geocoders import Nominatim
from geopy import distance
import math
import random
from chat.models import UserProfile, Friends, Messages

def errormessage(request,l):
    return render(request, 'accounts/showdata.html',{'l':l})

class Person1:
  def __init__(self,username, name, img,age,height,gender,country,city,education,religion):
    self.username=username
    self.name = name
    self.img=img
    self.age = age
    self.height=height
    self.gender=gender
    self.country=country
    self.city=city
    self.education=education
    self.religion=religion

# putting data in the home page
def home(request,pk=None):
    if pk:
        ruser = UserProfile.objects.get(pk=pk)
    else:
        ruser = request.user

        # jab koi request nhi karega
    user = UserProfile.objects.all()
    dic = list()
    
    for i in user:
        if ruser and ruser.username==i.username:
            print(i.username," is Logged IN!!!")
        else:
            name = i.name
            img=False
            age=False
            height=False
            gender=False
            country=False
            city=False
            education=False
            religion=False
            if(Show.objects.filter(username=i.username)):
                j= Show.objects.get(username=i.username)
                age = j.age
                height=j.height
                gender=j.gender
                country = j.Country
                city = j.City
                education = j.education
                religion = j.religion
            if(UploadedImage1.objects.filter(title=i.username)):
                im = UploadedImage1.objects.get(title=i.username)
                img = im.image
            if(name!=" "):
                dic.append(Person1(i.username,name,img,age,height,gender,country,city,education,religion))
    return render(request,'accounts/home.html',{'dic':dic})


# showing user profile
def profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    su = user.username
    args={}
    args['user']=user
    args['name']= UserProfile.objects.get(username=su).name
    if(UploadedImage1.objects.filter(title=su)):
        image = UploadedImage1.objects.get(title=su)
        args['img']=image
    if(Show.objects.filter(username=su)):
        prsnl = Show.objects.get(username=su)
        args['prsnl']=prsnl
    if(Preference_show.objects.filter(username=su)) :
        intr = Preference_show.objects.get(username=su)
        args['intr']=intr
        lang = (args['intr'].Language).values()
        t = ""
        langsize = len(lang)
        for j in range(0,langsize):
            i = lang[j]
            t = t + i['languages']
            if(j!=langsize-1):
                t = t + ", "
        args['languages'] = t
    return render(request, 'accounts/profile.html', args)


# change user password
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
        else:
            return redirect(reverse('change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

# reset the user password
def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "main/password/password_reset_email.txt"
                    c = {
                    "email":user.email,
                    'domain':'127.0.0.1:8000',
                    'site_name': 'Website',
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "user": user,
                    'token': default_token_generator.make_token(user),
                    'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect ("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="main/password/password_reset.html", context={"password_reset_form":password_reset_form})

def PasswordResetCompleteView(request):
    return redirect('/account/login')

# -------------------------------------------------------------

# Upload your profile photo
def index(request,pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    su = user.username
    if request.method == 'POST':
        submitted_form = UploadImageForm(request.POST, request.FILES)
        if submitted_form['title'].value()!=su:
            l = "User not created yet or username is not correct"
            return errormessage(request, l)
        if(UploadedImage1.objects.filter(title=su)):
            image = UploadedImage1.objects.get(title=su)
            image.delete()            
            
        if submitted_form.is_valid():
            submitted_form.save()
        return profile(request)

    form = UploadImageForm()
    context = {
        'form': form,
        'su':su,
    }
    return render(request, 'index.html', context=context)


# fill/edit your personal data
def my_form(request,pk=None):
    if request.method == "POST":
        if pk:
            user = User.objects.get(pk=pk)
        else:
            user = request.user
        su = user.username
        form = MyForm(request.POST,request.FILES)
        if(Show.objects.filter(username=su) and form['username'].value()==su):
            val = Show.objects.get(username=su)
            val.delete()
        if form.is_valid() and form['username'].value()==su:
            form.save()
            print("Your preference is submitted successfully...")
            return profile(request)
        else:
            l = "User not created yet or username is not correct"
            return errormessage(request, l)
    else:
        if(Show.objects.filter(username=request.user.username)):
            val = Show.objects.get(username=request.user.username)
            form  = MyForm(instance=val)
        else:
            form = MyForm(instance=request.user)
        return render(request, 'accounts/form.html', {'form': form})


# fill/edit your interest
def preference_form(request,pk=None):
    if request.method == "POST":
        if pk:
            user = User.objects.get(pk=pk)
        else:
            user = request.user
        su=user.username
        form = PreferenceForm(request.POST)
        if(Preference_show.objects.filter(username=su) and form['username'].value()==su):
            val = Preference_show.objects.get(username=su)
            val.delete()
        if form.is_valid() and form['username'].value()==su:
            form.save()
            print("Your preference is submitted successfully...")
            return profile(request)
        else:
            l = "User not created yet or username is not correct"
            return errormessage(request, l)
    else:
        if(Preference_show.objects.filter(username=request.user.username)):
            val = Preference_show.objects.get(username=request.user.username)
            form  = PreferenceForm(instance=val)
        else:
            form = PreferenceForm(instance=request.user)
        return render(request, 'accounts/form.html', {'form': form})

# Recommendation
def falseRecommendation(request):
    l = "Finding your best match..."
    return render(request,'accounts/waitrecommendation.html',{'l':l})

def showRecommendation(request,pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    su = user.username
    args={}
    args['username']=su
    args['interested_data']=False
    args['prsnl_data']=False

    if(Show.objects.filter(username=su)):
        prsnl = Show.objects.get(username=su)
        args['prsnl_data']=True
        args['age']=prsnl.age
        args['height']=prsnl.height
        args['gender']=prsnl.gender
        args['Country']=prsnl.Country
        args['City']=prsnl.City
        args['education']=prsnl.education
        args['religion']=prsnl.religion
        args['Distance']=prsnl.Distance
      
    if(Preference_show.objects.filter(username=su)) :
        intr = Preference_show.objects.get(username=su)
        args['interested_data']=True

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% block body %}
<div class="container">
<form method="post">
      {% csrf_token %}
      {{ form.as_p }}
  <button type="submit">Submit</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

{% block body %}
<div class="card" style="text-align:center;">
        <form method="POST" action="" enctype="=multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
</div>

{% endblock %}
</html>

accounts/templates/accounts/home.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

<style>
   .view {
     width: 350px;
     height: 270px;
     margin: 10px;
     float: left;
     border: 10px solid #fff;
     overflow: hidden;
     position: relative;
     text-align: center;
     -webkit-box-shadow: 1px 1px 2px #e6e6e6;
     -moz-box-shadow: 1px 1px 2px #e6e6e6;
     box-shadow: 1px 1px 2px #e6e6e6;
     cursor: default;
  }
  .view .mask,.view .content {
     width: 350px;
     height: 270px;
     position: absolute;
     overflow: hidden;
     top: 0;
     left: 0;
  }
  .view img {
     display: block;
  /*   position: relative;*/
  }
  .view h2 {
     text-transform: uppercase;
     color: #fff;
     text-align: center;
     position: relative;
     font-size: 17px;
     padding: 2px;
     background: rgba(0, 0, 0, 0.8);
  /*   margin: 20px 0 0 0;*/
  }
  
  .view h6 {
     font-family: Georgia, serif;
     font-style: italic;
     font-size: 16px;
     position: relative;
     color: #fff;
  /*   padding: 10px 20px 20px;*/
     text-align: center;
  }
  
  .view-fourth img {
     -webkit-transition: all 0.4s ease-in-out 0.2s;
     -moz-transition: all 0.4s ease-in-out 0.2s;
     -o-transition: all 0.4s ease-in-out 0.2s;
     -ms-transition: all 0.4s ease-in-out 0.2s;
     transition: all 0.4s ease-in-out 0.2s;
     -ms-filter: "progid: DXImageTransform.Microsoft.Alpha(Opacity=100)";
     filter: alpha(opacity=100);
     opacity: 1;
  }
  .view-fourth .mask {
     background-color: rgba(0,0,0,0.8);
     -ms-filter: "progid: DXImageTransform.Microsoft.Alpha(Opacity=0)";
     filter: alpha(opacity=0);
     opacity: 0;
     -webkit-transform: scale(0) rotate(-180deg);
     -moz-transform: scale(0) rotate(-180deg);
     -o-transform: scale(0) rotate(-180deg);
     -ms-transform: scale(0) rotate(-180deg);
     transform: scale(0) rotate(-180deg);
     -webkit-transition: all 0.4s ease-in;
     -moz-transition: all 0.4s ease-in;
     -o-transition: all 0.4s ease-in;
     -ms-transition: all 0.4s ease-in;
     transition: all 0.4s ease-in;
     -webkit-border-radius: 0px;
     -moz-border-radius: 0px;
     border-radius: 0px;
  }
  
  .view-fourth:hover .mask {
     -ms-filter: "progid: DXImageTransform.Microsoft.Alpha(Opacity=100)";
     filter: alpha(opacity=100);
     opacity: 1;
     -webkit-transform: scale(1) rotate(0deg);
     -moz-transform: scale(1) rotate(0deg);
     -o-transform: scale(1) rotate(0deg);
     -ms-transform: scale(1) rotate(0deg);
     transform: scale(1) rotate(0deg);
     -webkit-transition-delay: 0.2s;
     -moz-transition-delay: 0.2s;
     -o-transition-delay: 0.2s;
     -ms-transition-delay: 0.2s;
     transition-delay: 0.2s;
  } 
  .view-fourth:hover img {
     -webkit-transform: scale(0);
     -moz-transform: scale(0);
     -o-transform: scale(0);
     -ms-transform: scale(0);
     transform: scale(0);
     -ms-filter: "progid: DXImageTransform.Microsoft.Alpha(Opacity=0)";
     filter: alpha(opacity=0);
     opacity: 0;
     -webkit-transition-delay: 0s;
     -moz-transition-delay: 0s;
     -o-transition-delay: 0s;
     -ms-transition-delay: 0s;
     transition-delay: 0s;
  }
  .view-fourth:hover h2,
  .view-fourth:hover p,
  .view-fourth:hover a.info {
     -ms-filter: "progid: DXImageTransform.Microsoft.Alpha(Opacity=100)";
     filter: alpha(opacity=100);
     opacity: 1;
     -webkit-transition-delay: 0.5s;
     -moz-transition-delay: 0.5s;
     -o-transition-delay: 0.5s;
     -ms-transition-delay: 0.5s;
     transition-delay: 0.5s;
  }
  
  .view a.info {
     display: inline-block;
     text-decoration: none;
     padding: 7px 14px;
     background: #000;
     color: #fff;
     text-transform: uppercase;
     -webkit-box-shadow: 0 0 1px #000;
     -moz-box-shadow: 0 0 1px #000;
     box-shadow: 0 0 1px #000;
  }
  </style>
<!-- style="width: 100%; position: fixed;z-index: 1;" -->
   <nav class="navbar navbar-expand-sm bg-dark navbar-dark" >
     <div id="navbar" class="navbar-collapse collapse">
     {% if user.is_authenticated %}
    <ul class="col text-center">
       <button type="button" class="btn btn-link"><a href="/account"><h3>Home</h3></a></button>
       <button type="button" class="btn btn-link"><a href="/account/profile"><h3>View Profile</h3></a></button>
       <button type="button" class="btn btn-link"><a href="/account/recommendation"><h3>Recommendation</h3></a></button>
       <button type="button" class="btn btn-link"><a href="/chatstart"><h3>Chat</h3></a></button>
       <button type="button" class="btn btn-link"><a href="/editprofile/"><h3>Edit Profile</h3></a></button>
       <button type="button" class="btn btn-link"><a href="/account/change_password"><h3>Change Password</h3></a></button>
      <button type="button" class="btn btn-link"><a href="/account/logout"><h3>Log Out</h3></a></button>
      </ul>

      {% else %}

      <ul class="col text-center">
            <button type="button" class="btn btn-link"><a href="/account"><h3>Home</h3></a></button>
          <button type="button" class="btn btn-link"><a href="/login"><h3>Login</h3></a></button>
          <button type="button" class="btn btn-link"><a href="/signup"><h3>Register</h3></a></button>
          <button type="button" class="btn btn-link"><a href="/account/reset-password"><h3>Reset Password</h3></a></button>
      </ul>

      {% endif %}

      </div>
  </nav>

  <div class="container">
   {% for i in dic %}
    <div class="main">
      <div class="view view-fourth">
        {% if i.img %}
            <img width="300px" height="250px" src="{{i.img.url}}" />
         {% else %}
             <img width="350px" height="250px" src="{% static 'temp.webp' %}" />
         {% endif %}
        <div class="mask">
          <h2>Name: {{i.name}}</h2>
          {% if i.age %}
          <h6>Age: {{i.age}}</h6>
          <h6>Gender: {{i.gender}}</h6>
          <h6>Height: {{i.height}}</h6>
          <h6>Religion: {{i.religion}}</h6>
          <h6>Education: {{i.education}}</h6>
          <h6>City: {{i.city}}</h6>
          <h6>Country: {{i.country}}</h6>
          {% endif %}
          <button type="button" class="btn btn-outline-success">
          <a href="/addfriend/{{i.username}}">Add Friend</a>
         </button>
        </div>
      </div>            
    </div>
    {% endfor %}
  </div> 

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
<h1>Welcome</h1>
<p>You can log in here</p>
<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <!-- <button type="submit">Login</button> -->
  <button type="submit"><a href="/account/profile"><h3>Submit</h3></a></button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Logged out</h1>
  <p>you have logged out!</p>
  </div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
 <h2 class="font-weight-bold mt-3">Password reset complete</h2>
        <hr>
        <p>Your password has been set. You may go ahead and log in now.</p>                 
        <a href="/account/login" class="btn btn-primary">Log in</a>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
 <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
    <hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
             {{ form.as_p }}                   
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h2 class="font-weight-bold mt-3">Password reset sent</h2>
        <hr>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
</div>
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
  <h1>Register</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="button">Submit</button>
</form>
</div>
{% endblock %}

accounts/templates/accounts/showdata.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/button.css' %}">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
{% block body %}

<!-- {% if user.is_authenticated %}
<div style="text-align:center;">
 <button type="button"><a href="/account/load">Upload/edit your photo</a></button>
<button type="button"><a href="/account/form">fill/edit your data</a></button>
<button type="button"><a href="/account/interested">fill/edit your interest</a></button>
</div>
 {% endif %} -->

<div style="text-align:center;">

<h2>{{l}}</h2>

</div>
{% endblock %}
</html>

accounts/templates/accounts/showimage.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/button.css' %}">
</head>
{% block body %}

<div class="row" style="text-align:center;">
        <div class="col-12">
            <form method="post" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="row">
                    <div class="col-6">
                        <label for="id_title">Title:</label> <input placeholder="Player First Name" type="text" name="title" maxlength="100" required="" id="id_title">
                    </div>
                </div>
                <div class="row">
                    <div class="file-upload">
                        <div class="image-upload-wrap">
                            <input class="file-upload-input" type='file' onchange="readURL(this);" name="image" accept="image/*" required="" id="id_image"/>
                        </div>
                    </div>
                </div>
                <button class="submit-btn btn btn-primary" type="submit">Submit</button> 
            </form>
        </div>
    </div>
{% endblock %}
</html>